# Default target: override with --target or set your own in ~/.cargo/config.toml
# vals:
#   aarch64-linux-android    (arm64-v8a)
#   armv7-linux-androideabi  (armeabi-v7a)
#   x86_64-linux-android     (for x86_64 emulator)
#   i686-linux-android       (x86 emulator)
# [build]
# target = "aarch64-linux-android"
